### PR TITLE
Use single branch updates

### PR DESCRIPTION
**Pull request by studouglas-scx**
Goal: have a single PR/branch that contains all scala steward updates. This way devs only need to approve a single PR per week rather than being overloaded. This is something scala-steward does not intend to implement.

This seems to work when I was playing around with it against the CRM repos, but it's pretty sketchy so I wouldn't be surprised if there are issues.

### CODE REVIEW

**Comment by steve-scx** [comment]
Now that's spicy!! 

Regarding the comment: https://github.com/scala-steward-org/scala-steward/issues/413#issuecomment-585410159

> I don't like bundling updates into one PR mostly because it complicates the implementation of Scala Steward and would raise a set of new problems / questions for which I don't see good solutions. Here are a few issues I see:
>
> The set of updates that are included in such a PR depend on the time it was created. A second later there might be another dependency with an update which would have been included in the PR. On the next Scala Steward run, should this dependency be included in this PR or should a new one be created? Would the new one include the updates of the previous PR?

Seems like you're choosing to just add to the existing PR if it exists, which seems fine to me.

> We loose the ability to detect if there is already a PR for a particular update. Currently it is possible to delete the complete persistent state Scala Steward created and run it again and it would find the PRs it created before again and would not create duplicated PRs for the same update. We can do this because each update corresponds to a distinct branch name which we can search for. I don't see how this could be done when updates are bundled in one PR.

How are you handling this?

> A lot of new code that needs to be maintained. The current code assume that one update corresponds to one branch and one PR. A bundle PR would break that assumption and there needs to be code that accounts for that. I don't think that the benefits of this feature outweigh the maintenance costs.

LOL 

Any idea what they're talking about here?

**Review by steve-scx — APPROVED** [review]

**Review by mani-streetcontxt — APPROVED** [review]

**Comment by angelo-streetcontxt** [comment]
@steve-scx  `Regarding the comment: scala-steward-org#413 (comment)`

I think you have to consider their target audience. Scala Steward was written for OSS scala projects to stay up to date with other OSS scala projects, the fact that it lets us do this sort of thing is a happy side effect as opposed to it's main goal

**Review by angelo-streetcontxt — APPROVED** [review]
This is awesome work, and especially now that all the PRs have to have approval to merge, it'll hopefully help keep the overhead down.

**Comment by steve-scx** [comment]
> @steve-scx `Regarding the comment: scala-steward-org#413 (comment)`
> 
> I think you have to consider their target audience. Scala Steward was written for OSS scala projects to stay up to date with other OSS scala projects, the fact that it lets us do this sort of thing is a happy side effect as opposed to it's main goal

Agreed, just want to cover our bases on the specific reasons the author gave in that comment, since they were quite adamant it would be a big lift and lots of code, yet Stu's commit is tiny and simple. Maybe it's because there are potentially many variations people could want here, and we're just hard-coding one particular approach?

**Comment by studouglas-scx** [comment]
@steve-scx there are few code changes here, but I'm basically ignoring a lot of the config options, and it's definitely not optimal at all. To do this properly would require a decent amount of work.

Couple examples:
- this still pushes a commit (2 if it does a merge commit) per update, so we're still using a ton of circle builds. Ideally we just commit all locally and do one push at the end, but that seemed complex.
- I'm not sure how this will handle conflicts
- the PR name just uses the first commit's name so isn't accurate. Same with the PR body -- though I think it references the last committed update
- I don't think labels will work as expected (i.e. patch vs major vs minor)

Ideas for future enhancements:
- it'd be nice to commit everything then push (perf. improvement / save circle build time)
- using 3 branches for the different version bumps would be nice, e.g. one for patch, minor, and major

**Comment by steve-scx** [comment]
> @steve-scx there are few code changes here, but I'm basically ignoring a lot of the config options, and it's definitely not optimal at all. To do this properly would require a decent amount of work.
> 
> Couple examples:
> 
> * this still pushes a commit (2 if it does a merge commit) per update, so we're still using a ton of circle builds. Ideally we just commit all locally and do one push at the end, but that seemed complex.
> * I'm not sure how this will handle conflicts
> * the PR name just uses the first commit's name so isn't accurate. Same with the PR body -- though I think it references the last committed update
> * I don't think labels will work as expected (i.e. patch vs major vs minor)
> 
> Ideas for future enhancements:
> 
> * it'd be nice to commit everything then push (perf. improvement / save circle build time)
> * using 3 branches for the different version bumps would be nice, e.g. one for patch, minor, and major

Awesome! Might be good to record that in the README.md?

**Review by tim-scx — APPROVED** [review]
Nice 👍 

~~scala-steward~~ scala-stuart 🚀

**Comment by studouglas-scx** [comment]
Update: it was actually easy to separate branches per update level. Also fixed the PR title / body. This should make it easier to debug test failures (since presumably major updates should break tests much more than patches).

This is how it looks in action: https://github.com/street-contxt-private/crm-store/pulls

**Pull request merged**
